services:
  llm_guard_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./config/scanners.yml:/home/user/app/config/scanners.yml
